# frozen_string_literal: true

require_relative "openusd/version"
require_relative "openusd/errors"
require_relative "openusd/path"
require_relative "openusd/value"
require_relative "openusd/types"
require_relative "openusd/attribute_spec"
require_relative "openusd/relationship_spec"
require_relative "openusd/prim_spec"
require_relative "openusd/format/registry"
require_relative "openusd/layer"
require_relative "openusd/format/usda/lexer"
require_relative "openusd/format/usda/parser"
require_relative "openusd/format/usda/writer"
require_relative "openusd/asset_resolver"
require_relative "openusd/composition"
require_relative "openusd/metadata_view"
require_relative "openusd/attribute"
require_relative "openusd/relationship"
require_relative "openusd/prim"
require_relative "openusd/stage"
require_relative "openusd/format/usdz/reader"
require_relative "openusd/format/usdz/writer"
require_relative "openusd/schema/base"
require_relative "openusd/schema/xform"
require_relative "openusd/schema/mesh"
require_relative "openusd/schema/camera"
require_relative "openusd/schema/material"
require_relative "openusd/schema/scope"

module OpenUSD
end

# Compatibility for the name generated by early versions of the gem skeleton.
Openusd = OpenUSD unless defined?(Openusd)
