# frozen_string_literal: true

require_relative "openusd/version"
require_relative "openusd/errors"
require_relative "openusd/path"
require_relative "openusd/value"
require_relative "openusd/types"

module OpenUSD
end

# Compatibility for the name generated by early versions of the gem skeleton.
Openusd = OpenUSD unless defined?(Openusd)
